apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kepler-prometheus-exporter
  namespace: kepler
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kepler
    app.kubernetes.io/version: release-0.7.12
    helm.sh/chart: kepler-0.5.13
    release: prometheus
  annotations:
    meta.helm.sh/release-name: kepler
    meta.helm.sh/release-namespace: kepler
spec:
  attachMetadata:
    node: false
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler
  namespaceSelector:
    matchNames:
      - kepler
  endpoints:
    - interval: 1s
      scrapeTimeout: 2s
      port: http
      path: /metrics
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
          action: replace
          regex: (.*)
          replacement: $1