prometheus:
  prometheusSpec:
    scrapeInterval: 3s
    scrapeTimeout: 3s
    evaluationInterval: 5s
    
    # Monitor settings
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    
    # Additional settings to ensure they're applied
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}