prometheus:
  prometheusSpec:
    scrapeInterval: 2s
    scrapeTimeout: 1s
    evaluationInterval: 5s
    
    # Monitor settings
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    
    # Additional settings to ensure they're applied
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}

    scrape_configs:
    - job_name: cadvisor
      scrape_interval: 5s
      static_configs:
      - targets:
        - cadvisor:8080