apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-complete
  labels:
    ray.io/cluster: raycluster-complete
spec:
  rayVersion: '2.9.0'
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      metadata:
        labels:
          ray.io/cluster: raycluster-complete
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray-ml:2.9.0
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          - containerPort: 8000
            name: serve
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 10
    groupName: small-group
    rayStartParams: {}
    template:
      metadata:
        labels:
          ray.io/cluster: raycluster-complete
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray-ml:2.9.0
---
apiVersion: v1
kind: Service
metadata:
  name: raycluster-complete-head-svc
  labels:
    ray.io/cluster: raycluster-complete
spec:
  selector:
    ray.io/cluster: raycluster-complete
    component: head
  ports:
  - protocol: TCP
    port: 8265
    targetPort: 8265


