# filepath: /home/felix/Documents/Studium TU/Masterarbeit/ms_project/ray/kuberay-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberay-operator
  template:
    metadata:
      labels:
        app: kuberay-operator
    spec:
      containers:
      - name: kuberay-operator
        image: rayproject/kuberay-operator:latest
        ports:
        - containerPort: 8080
        command:
        - /manager
        args:
        - --enable-leader-election