apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-pytorch-mnist
spec:
  entrypoint: python /app/script.py
  jobSubmitterTemplateSpec:
    spec:
      containers:
      - name: ray-job-submitter
        image: ray-mnist:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: script-volume
          mountPath: /app
      volumes:
      - name: script-volume
        configMap:
          name: ray-script
  driverTemplateSpec:  # Add this section
    spec:
      containers:
        - name: ray-driver
          image: ray-mnist:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: script-volume
            mountPath: /app
      volumes:
      - name: script-volume
        configMap:
          name: ray-script

  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.41.0'
    headGroupSpec:
      rayStartParams: {}
      # Pod template
      template:
        spec:
          volumes:  # Move this here
          - name: script-volume
            configMap:
              name: ray-script
          containers:  # Only one containers section
          - name: ray-head
            image: ray-mnist:latest 
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
            resources:
              limits:
                cpu: "2"
                memory: "2Gi"
              requests:
                cpu: "2"
                memory: "1Gi"
            volumeMounts:  # This stays in the container
            - name: script-volume
              mountPath: /app
    workerGroupSpecs:
      - replicas: 3
        minReplicas: 1
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        # Pod template
        template:
          spec:
            containers:
              - name: ray-worker
                image: ray-mnist:latest 
                imagePullPolicy: IfNotPresent
                resources:
                  limits:
                    cpu: "2"
                    memory: "2Gi"
                  requests:
                    cpu: "1"
                    memory: "1Gi"
