apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-snapshot-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-snapshot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi