---
apiVersion: batch/v1
kind: Job
metadata:
  name: study-creator
  namespace: st-felixgraf2
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ise-knode6
      restartPolicy: OnFailure
      containers:
        - name: study-creator
          image: docker.io/gafex/optuna-mnist:ise-kube
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - -e
          - -x
          - |
            optuna create-study --skip-if-exists --direction maximize \
            --study-name "k8s_mlflow" --storage \
            "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
          envFrom:
            - secretRef:
                name: postgres-secrets
---
